"""no-op cleanup revision after stale autogenerated migration

Revision ID: 4fa62e80393c
Revises: 0021_add_therapist_and_clinic_branding_fields
Create Date: 2026-04-30 00:16:19.937571

This revision previously contained autogenerated DDL from an inconsistent
database state. It attempted to recreate existing tables such as `clinics`
and mutate unrelated constraints/indexes out of order. That made
`alembic upgrade head` non-deterministic both on clean databases and on
partially reset environments.

The migration is intentionally a no-op so the Alembic history remains
continuous while schema creation continues to be driven by the coherent
revisions up to `0021_add_therapist_and_clinic_branding_fields`.
"""

from typing import Sequence, Union


revision: str = "4fa62e80393c"
down_revision: Union[str, Sequence[str], None] = "0021_add_therapist_and_clinic_branding_fields"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
